---
appveyor.yml:
  delete: true
rubocop.yml:
  include_todos: true

spec/spec_helper.rb:
  spec_overrides:
  - require 'spec_helper_local'
  coverage_report: true
Rakefile:
  changelog_max_issues: 500
  extra_disabled_lint_checks:
    - anchor_resource
    - params_empty_string_assignment
