name: "Auto release"

on: [pull_request]

env:
  HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
  HONEYCOMB_DATASET: litmus tests
  SERVICE_URL: https://facade-main-6f3kfepqcq-ew.a.run.app/v1/provision
  CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  auto_release:
    name: "Automatic release prep"
    runs-on: ubuntu-20.04

    steps:
    - name: "Honeycomb: Start recording"
      uses: kvrhdn/gha-buildevents@5be4636b81803713c94d7cb7e3a4b85d759df112 # pin@v1.0.2
      with:
        apikey: ${{ env.HONEYCOMB_WRITEKEY }}
        dataset: ${{ env.HONEYCOMB_DATASET }}
        job-status: ${{ job.status }}

    - name: "Honeycomb: start first step"
      run: |
        echo STEP_ID="auto-release" >> $GITHUB_ENV
        echo STEP_START=$(date +%s) >> $GITHUB_ENV

    - name: "Checkout Source"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Activate Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6"

    - name: "Bundle install"
      run: |
        echo "gem 'pdk'" >> Gemfile
        bundle install 

    - name: "PDK Release prep"
      run: |
        pdk release prep --force

    - name: "Commit changes"
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-Release prep"

    - name: "Get Version"
      id: gv
      run: |
        echo "::set-output name=ver::$(cat metadata.json | jq .version)"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Auto-release prep"
        branch: "release-prep"
        delete-branch: true
        title: "Auto-release prep ${{ steps.gv.outputs.ver }}"
        labels: "maintenance"

    - name: PR outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
