name: "Spec Tests"

on:
  workflow_dispatch:
  pull_request:

env:
  HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
  HONEYCOMB_DATASET: litmus tests
  SERVICE_URL: https://facade-main-6f3kfepqcq-ew.a.run.app/v1/provision

jobs:
  Spec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    env:
      BUILDEVENT_FILE: '../buildevents.txt'
      PUPPET_GEM_VERSION: ${{ matrix.puppet_version }}
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Fetch PDK Docker container
        run: docker pull puppet/pdk

      - name: Run PDK Validate
        run: docker run -v $(pwd):/root puppet/pdk validate
