name: "Ubuntu user data scirpt validation"

on: [pull_request]


env:
  SERVICE_URL: "https://facade-maint-grep-command-exit-code-fix-6f3kfepqcq-ew.a.run.app/v1/provision"

jobs:
  Provision:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Activate Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Provision Ubuntu 2004
        run: |
          bundle exec rake "litmus:provision[provision_service,ubuntu-2004-lts]"
      
      - name: Provision Ubuntu 2204 ARM
        run: |
          bundle exec rake "litmus:provision[provision_service,ubuntu-2204-lts-arm64]"

      - name: Remove test environment
        if: always()
        continue-on-error: true
        run: |
          bundle exec rake litmus:tear_down
